# fly.toml app configuration file generated for spectrum on 2023-10-22T21:58:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spectrum"
primary_region = "ams"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  # release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "spectrum.fly.dev"
  PORT = "8080"
  DATABASE_PATH = "/data/spectrum.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[mounts]
    source="spectrum_data"
    destination="/data"
