defmodule Spotifyr.Repo.Migrations.AddSpotifyCreds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :spotify_access_token, :text
      add :spotify_refresh_token, :text
    end
  end

  def down do
    alter table(:users) do
      remove :spotify_refresh_token
      remove :spotify_access_token
    end
  end
end
