defmodule Spotifyr.Repo.Migrations.RemoveSpotifyTokenTimestamp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :spotify_last_refresh
    end

    #
  end

  def down do
    alter table(:users) do
      # This is the `down` migration of the statement:
      #
      # remove :spotify_last_refresh
      #
      #
      add :spotify_last_refresh, :utc_datetime
    end

    #
  end
end
